# -*- coding: utf-8 -*-

# 8.5 Impuestos registrados en la Factura Electrónica

TAX_TYPES = {
    "01": "VALOR TOTAL DE IVA",
    "02": "VALOR TOTAL DE IMPUESTO AL CONSUMO",
    "03": "VALOR TOTAL DE ICA",
    "04": "VALOR TOTAL DE IMPUESTO NACIONAL AL CONSUMO",
    "05": "CODIGO RESERVADO PARA LA DIAN",
    "06": "CODIGO RESERVADO PARA LA DIAN",
    "07": "CODIGO RESERVADO PARA LA DIAN",
    "08": "CODIGO RESERVADO PARA LA DIAN",
    "09": "CODIGO RESERVADO PARA LA DIAN",
}
