# -*- coding: utf-8 -*-

# 8.7. Monedas

CURRENCIES = {
    "AED": "United Arab Emi",
    "AFA": "Afghanistan, Af",
    "AUD": "Australia, Doll",
    "AWG": "Aruba, Guilders",
    "AZM": "Azerbaijan, Man",
    "BAM": "Bosnia and Herz",
    "BBD": "Barbados, Dolla",
    "BDT": "Bangladesh, Tak",
    "BGN": "Bulgaria, Leva",
    "BHD": "Bahrain, Dinars",
    "BIF": "Burundi, Francs",
    "BMD": "Bermuda, Dollar",
    "BND": "Brunei Darussal",
    "BOB": "Bolivia, Bolivi",
    "BRL": "Brazil, Brazil",
    "BSD": "Bahamas, Dollar",
    "BTN": "Bhutan, Ngultru",
    "BWP": "Botswana, Pulas",
    "BYR": "Belarus, Rubles",
    "BZD": "Belize, Dollars",
    "CAD": "Canada, Dollars",
    "CDF": "Congo/Kinshasa",
    "CHF": "Switzerland, Fr",
    "CLP": "Chile, Pesos",
    "CNY": "China, Yuan Ren",
    "COP": "Colombia, Pesos",
    "CRC": "Costa Rica, Col",
    "CUP": "Cuba, Pesos",
    "CVE": "Cape Verde, Esc",
    "CYP": "Cyprus, Pounds",
    "CZK": "Czech Republic",
    "DJF": "Djibouti, Franc",
    "DKK": "Denmark, Kroner",
    "DOP": "Dominican Repub",
    "DZD": "Algeria, Algeri",
    "EEK": "Estonia, Krooni",
    "EGP": "Egypt, Pounds",
    "ERN": "Eritrea, Nakfa",
    "ETB": "Ethiopia, Birr",
    "FJD": "Fiji, Dollars",
    "FKP": "Falkland Island",
    "GBP": "United Kingdom",
    "GEL": "Georgia, Lari",
    "GGP": "Guernsey, Pound",
    "GHC": "Ghana, Cedis",
    "GIP": "Gibraltar, Poun",
    "GMD": "Gambia, Dalasi",
    "GNF": "Guinea, Francs",
    "GTQ": "Guatemala, Quet",
    "GYD": "Guyana, Dollars",
    "HKD": "Hong Kong, Doll",
    "HNL": "Honduras, Lempi",
    "HRK": "Croatia, Kuna",
    "HTG": "Haiti, Gourdes",
    "HUF": "Hungary, Forint",
    "IDR": "Indonesia, Rupi",
    "ILS": "Israel, New She",
    "IMP": "Isle of Man, Po",
    "INR": "India, Rupees",
    "IQD": "Iraq, Dinars",
    "IRR": "Iran, Rials",
    "ISK": "Iceland, Kronur",
    "JMD": "Jamaica, Dollar",
    "JOD": "Jordan, Dinars",
    "JPY": "Japan, Yen",
    "KES": "Kenya, Shilling",
    "KGS": "Kyrgyzstan, Som",
    "KHR": "Cambodia, Riels",
    "KMF": "Comoros, Francs",
    "KPW": "Korea (North)",
    "KRW": "Korea (South)",
    "KWD": "Kuwait, Dinars",
    "KYD": "Cayman Islands,",
    "KZT": "Kazakstan, Teng",
    "LAK": "Laos, Kips",
    "LBP": "Lebanon, Pounds",
    "LKR": "Sri Lanka, Rupe",
    "MGA": "Madagascar, Ari",
    "MKD": "Macedonia, Dena",
    "MMK": "Myanmar (Burma)",
    "MNT": "Mongolia, Tugri",
    "MOP": "Macau, Patacas",
    "MRO": "Mauritania, Oug",
    "MTL": "Malta, Liri",
    "MUR": "Mauritius, Rupe",
    "MVR": "Maldives (Maldi",
    "MWK": "Malawi, Kwachas",
    "MXN": "Mexico, Pesos",
    "MYR": "Malaysia, Ringg",
    "MZM": "Mozambique, Met",
    "NAD": "Namibia, Dollar",
    "NGN": "Nigeria, Nairas",
    "NIO": "Nicaragua, Gold",
    "NOK": "Norway, Krone",
    "NPR": "Nepal, Nepal Ru",
    "NZD": "New Zealand, Do",
    "OMR": "Oman, Rials",
    "PAB": "Panama, Balboa",
    "PEN": "Peru, Nuevos So",
    "PGK": "Papua New Guine",
    "PHP": "Philippines, Pe",
    "PKR": "Pakistan, Rupee",
    "PLN": "Poland, Zlotych",
    "PYG": "Paraguay, Guara",
    "QAR": "Qatar, Rials",
    "ROL": "Romania, Lei",
    "RSD": "Serbia, Dinars",
    "RUB": "Russia Rubles",
    "RWF": "Rwanda, Rwanda",
    "SAR": "Saudi Arabia, R",
    "SBD": "Solomon Islands",
    "SCR": "Seychelles, Rup",
    "SDD": "Sudan, Dinars",
    "SDG": "Sudan, Pounds",
    "SEK": "Sweden, Kronor",
    "SGD": "Singapore, Doll",
    "SHP": "Saint Helena, P",
    "SIT": "Slovenia, Tolar",
    "SKK": "Slovakia, Korun",
    "SLL": "Sierra Leone, L",
    "SOS": "Somalia, Shilli",
    "SRD": "Suriname, Dolla",
    "STD": "Sao Tome and P",
    "SVC": "El Salvador, Co",
    "SYP": "Syria, Pounds",
    "SZL": "Swaziland, Emal",
    "THB": "Thailand, Baht",
    "TJS": "Tajik., Somo.",
    "TMT": "Turkmenistan, M",
    "TND": "Tunisia, Dinars",
    "TOP": "Tonga, Paanga",
    "TRY": "Turkey, Liras",
    "TTD": "Trinidad and To",
    "TVD": "Tuvalu, Tuvalu",
    "TWD": "Taiwan, New Dol",
    "TZS": "Tanzania, Shill",
    "UAH": "Ukraine, Hryvni",
    "UGX": "Uganda, Shillin",
    "UYU": "Uruguay, Pesos",
    "UZS": "Uzbekistan, Sum",
    "VEB": "Venezuela, Boli",
    "VEF": "Venez.Bol.Frte",
    "VND": "Viet Nam, Dong",
    "VUV": "Vanuatu, Vatu",
    "WST": "Samoa, Tala",
    "XAF": "C. Afri., Fra.",
    "XCD": "E. Car., Dol.",
    "XOF": "Africa, Francs",
    "XPF": "Polyn. Francs",
    "YER": "Yemen, Rials",
    "ZAR": "S. Afri., Rands",
    "ZMK": "Zamb., Kwachas",
    "ZWL": "Zimb., Dollars",
}
