# -*- coding: utf-8 -*-

# 8.8. Países

COUNTRIES = {
    "AD": "ANDORRA",
    "AE": "EMIRATOS ARABES UNIDOS",
    "AF": "AFGANISTAN",
    "AG": "ANTIGUA Y BARBUDA",
    "AI": "ANGUILA",
    "AL": "ALBANIA",
    "AM": "ARMENIA",
    "AO": "ANGOLA",
    "AQ": "ANTARTIDA",
    "AR": "ARGENTINA",
    "AS": "SAMOA AMERICANA",
    "AT": "AUSTRIA",
    "AU": "AUSTRALIA",
    "AW": "ARUBA",
    "AX": "ISLAS \u00c5LAND",
    "AZ": "AZERBAIYAN",
    "BA": "BOSNIA Y HERZEGOVINA",
    "BB": "BARBADOS",
    "BD": "BANGLADES",
    "BE": "BELGICA",
    "BF": "BURKINA FASO",
    "BG": "BULGARIA",
    "BH": "BAREIN",
    "BI": "BURUNDI",
    "BJ": "BENIN",
    "BL": "SAN BARTOLOME",
    "BM": "BERMUDAS",
    "BN": "BRUNEI DARUSSALAM",
    "BO": "BOLIVIA, ESTADO PLURINACIONAL DE",
    "BQ": "BONAIRE, SAN EUSTAQUIO Y SABA",
    "BR": "BRASIL",
    "BS": "BAHAMAS",
    "BT": "BUTAN",
    "BV": "ISLA BOUVET",
    "BW": "BOTSUANA",
    "BY": "BIELORRUSIA",
    "BZ": "BELICE",
    "CA": "CANADA",
    "CC": "ISLAS COCOS (KEELING)",
    "CD": "CONGO, LA REPUBLICA DEMOCRATICA DEL",
    "CF": "REPUBLICA CENTROAFRICANA",
    "CG": "CONGO",
    "CH": "SUIZA",
    "CI": "COSTA DE MARFIL",
    "CK": "ISLAS COOK",
    "CL": "CHILE",
    "CM": "CAMERUN",
    "CN": "CHINA, REPUBLICA POPULAR",
    "CO": "COLOMBIA",
    "CR": "COSTA RICA",
    "CU": "CUBA",
    "CV": "CABO VERDE",
    "CW": "CURAZAO",
    "CX": "ISLA DE NAVIDAD",
    "CY": "CHIPRE",
    "CZ": "REPUBLICA CHECA",
    "DE": "ALEMANIA",
    "DJ": "YIBUTI",
    "DK": "DINAMARCA",
    "DM": "DOMINICA",
    "DO": "REPUBLICA DOMINICANA",
    "DZ": "ARGELIA",
    "EC": "ECUADOR",
    "EE": "ESTONIA",
    "EG": "EGIPTO",
    "EH": "SAHARA OCCIDENTAL",
    "ER": "ERITREA",
    "ES": "ESPA\u00d1A",
    "ET": "ETIOPIA",
    "FI": "FINLANDIA",
    "FJ": "FIYI",
    "FK": "ISLAS FALKLAND (MALVINAS)",
    "FM": "MICRONESIA, ESTADOS FEDERADOS DE",
    "FO": "ISLAS FEROE",
    "FR": "FRANCIA",
    "GA": "GABON",
    "GB": "REINO UNIDO",
    "GD": "GRANADA",
    "GE": "GEORGIA",
    "GF": "GUAYANA FRANCESA",
    "GG": "GUERNSEY",
    "GH": "GHANA",
    "GI": "GIBRALTAR",
    "GL": "GROENLANDIA",
    "GM": "GAMBIA",
    "GN": "GUINEA",
    "GP": "GUADALUPE",
    "GQ": "GUINEA ECUATORIAL",
    "GR": "GRECIA",
    "GS": "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR",
    "GT": "GUATEMALA",
    "GU": "GUAM",
    "GW": "GUINEA-BISAU",
    "GY": "GUYANA",
    "HK": "HONG KONG",
    "HM": "ISLAS HEARD Y MCDONALD",
    "HN": "HONDURAS",
    "HR": "CROACIA",
    "HT": "HAITI",
    "HU": "HUNGRIA",
    "ID": "INDONESIA",
    "IE": "IRLANDA",
    "IL": "ISRAEL",
    "IM": "ISLA DE MAN",
    "IN": "INDIA",
    "IO": "TERRITORIO BRITANICO DEL OCEANO",
    "IQ": "IRAK",
    "IR": "IRAN, REPUBLICA ISLAMICA DE",
    "IS": "ISLANDIA",
    "IT": "ITALIA",
    "JE": "JERSEY",
    "JM": "JAMAICA",
    "JO": "JORDANIA",
    "JP": "JAPON",
    "KE": "KENIA",
    "KG": "KIRGUISTAN",
    "KH": "CAMBOYA",
    "KI": "KIRIBATI",
    "KM": "COMORAS",
    "KN": "SAN CRISTOBAL Y NIEVES",
    "KP": "COREA, REPUBLICA DEMOCRATICA POPULAR DE",
    "KR": "COREA, REPUBLICA DE",
    "KW": "KUWAIT",
    "KY": "ISLAS CAIMAN",
    "KZ": "KAZAJISTAN",
    "LA": "LAOS REPUBLICA DEMOCRATICA POPULAR LAO",
    "LB": "LIBANO",
    "LC": "SANTA LUCIA",
    "LI": "LIECHTENSTEIN",
    "LK": "SRI LANKA",
    "LR": "LIBERIA",
    "LS": "LESOTO",
    "LT": "LITUANIA",
    "LU": "LUXEMBURGO",
    "LV": "LETONIA",
    "LY": "LIBIA",
    "MA": "MARRUECOS",
    "MC": "MONACO",
    "MD": "MOLDAVIA, REPUBLICA DE",
    "ME": "MONTENEGRO",
    "MF": "SAN MARTIN (PARTE FRANCESA)",
    "MG": "MADAGASCAR",
    "MH": "ISLAS MARSHALL",
    "MK": "MACEDONIA, LA ANTIGUA REPUBLICA YUGOSLAVA DE",
    "ML": "MALI",
    "MM": "MYANMAR",
    "MN": "MONGOLIA",
    "MO": "MACAO",
    "MP": "ISLAS MARIANAS DEL NORTE",
    "MQ": "MARTINICA",
    "MR": "MAURITANIA",
    "MS": "MONTSERRAT",
    "MT": "MALTA",
    "MU": "MAURICIO",
    "MV": "MALDIVAS",
    "MW": "MALAUI",
    "MX": "MEXICO",
    "MY": "MALASIA",
    "MZ": "MOZAMBIQUE",
    "NA": "NABIMIA",
    "NC": "NUEVA CALEDONIA",
    "NE": "NIGER",
    "NF": "ISLA NORFOLK",
    "NG": "NIGERIA",
    "NI": "NICARAGUA",
    "NL": "PAISES BAJOS",
    "NO": "NORUEGA",
    "NP": "NEPAL",
    "NR": "NAURU",
    "NU": "NIUE",
    "NZ": "NUEVA ZELANDA",
    "OM": "OMAN",
    "PA": "PANAMA",
    "PE": "PERU",
    "PF": "POLINESIA FRANCESA",
    "PG": "PAPUA NUEVA GUINEA",
    "PH": "FILIPINAS",
    "PK": "PAKISTAN",
    "PL": "POLONIA",
    "PM": "SAN PEDRO Y MIQUELON",
    "PN": "PITCAIRN",
    "PR": "PUERTO RICO",
    "PS": "PALESTINA, ESTADO DE",
    "PT": "PORTUGAL",
    "PW": "PALAOS",
    "PY": "PARAGUAY",
    "QA": "QATAR",
    "RE": "REUNION",
    "RO": "RUMANIA",
    "RS": "SERBIA",
    "RU": "rusia !FEDERACION RUSA",
    "RW": "RUANDA",
    "SA": "ARABIA SAUDITA",
    "SB": "ISLAS SALOMON",
    "SC": "SEYCHELLES",
    "SD": "SUDAN",
    "SE": "SUECIA",
    "SG": "SINGAPUR",
    "SH": "SANTA HELENA, ASCENSION Y TRISTAN",
    "SI": "ESLOVENIA",
    "SJ": "SVALBARD Y JAN MAYEN",
    "SK": "ESLOVAQUIA",
    "SL": "SIERRA LEONA",
    "SM": "SAN MARINO",
    "SN": "SENEGAL",
    "SO": "SOMALIA",
    "SR": "SURINAM",
    "SS": "SUDAN DEL SUR",
    "ST": "SANTO TOME Y PRINCIPE",
    "SV": "EL SALVADOR",
    "SX": "SINT MAARTEN (PARTE NEERLANDESA)",
    "SY": "REPUBLICA ARABE DE SIRIA",
    "SZ": "SUAZILANDIA",
    "TC": "ISLAS TURCAS Y CAICOS",
    "TD": "CHAD",
    "TF": "TERRITORIOS AUSTRALES FRANCESES",
    "TG": "TOGO",
    "TH": "TAILANDIA",
    "TJ": "TAYIKISTAN",
    "TK": "TOKELAU",
    "TL": "TIMOR-LESTE",
    "TM": "TURKMENISTAN",
    "TN": "TUNEZ",
    "TO": "TONGA",
    "TR": "TURQUIA",
    "TT": "TRINIDAD Y TOBAGO",
    "TV": "TUVALU",
    "TW": "TAIWAN, PROVINCIA DE CHINA",
    "TZ": "TANZANIA, REPUBLICA UNIDA DE",
    "UA": "UCRANIA",
    "UG": "UGANDA",
    "UM": "ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS",
    "US": "ESTADOS UNIDOS",
    "UY": "URUGUAY",
    "UZ": "UZBEKISTAN",
    "VA": "Vaticano SANTA SEDE (CIUDAD ESTADO VATICANO)",
    "VC": "SAN VICENTE Y LAS GRANADINAS",
    "VE": "VENEZUELA, REPUBLICA BOLIVARIANA DE",
    "VG": "ISLAS VIRGENES BRITANICAS",
    "VI": "ISLAS VIRGENES DE LOS ESTADOS UNIDOS",
    "VN": "VIET NAM",
    "VU": "VANUATU",
    "WF": "WALLIS Y FUTUNA",
    "WS": "SAMOA",
    "YE": "YEMEN",
    "YT": "MAYOTTE",
    "ZA": "SUDAFRICA",
    "ZM": "ZAMBIA",
    "ZW": "ZIMBABUE",
}
