# -*- coding: utf-8 -*-

# 8.13. Tipos de Representación

REPRESENTATION_TYPES = {
    "R-00-PN": "No obligado a registrarse en el RUT PN",
    "R-01-PN": "Administrador judicial PN",
    "R-02-PN": "Administrador privado PN",
    "R-03-PN": "Agente exclusivo de negocios en Colombia PN",
    "R-04-PN": "Agente oficioso PN",
    "R-05-PN": "Albacea PN",
    "R-06-PN": "Apoderado especial PN",
    "R-07-PN": "Apoderado general PN",
    "R-08-PN": "Asignatario PN",
    "R-09-PN": "Comunero PN",
    "R-10-PN": "Curador PN",
    "R-11-PN": "Donatario PN",
    "R-12-PN": "Factor PN",
    "R-14-PN": "Heredero con administración de bienes PN",
    "R-15-PN": "Liquidador PN",
    "R-16-PN": "Mandatario PN",
    "R-17-PN": "Padre PN",
    "R-21-PN": "Tutor PN",
    "R-22-PN": "Representante aduanero PN",
    "R-23-PN": "Liquidador suplente PN",
    "R-24-PN": "Depositario Provisional PN",
    "R-25-PN": "Agente Interventor PN",
    "R-28-PN": "Heredero designado PN",
    "R-29-PN": "Persona Natural sin residencia en Colombia con EP PN",
    "R-99-PN": "Otro tipo de responsable PN",
    "R-01-PJ": "Administrador judicial PJ",
    "R-02-PJ": "Administrador privado PJ",
    "R-03-PJ": "Agente exclusivo de negocios en Colombia PJ",
    "R-06-PJ": "Apoderado especial PJ",
    "R-07-PJ": "Apoderado general PJ",
    "R-09-PJ": "Comunero PJ",
    "R-12-PJ": "Factor PJ",
    "R-13-PJ": "Funcionario delegado para cumplir deberes formales PJ",
    "R-15-PJ": "Liquidador PJ",
    "R-16-PJ": "Mandatario PJ",
    "R-18-PJ": "Representante legal principal PJ",
    "R-19-PJ": "Representante legal suplente PJ",
    "R-20-PJ": "Síndico PJ",
    "R-22-PJ": "Representante aduanero PJ",
    "R-23-PJ": "Liquidador suplente PJ",
    "R-24-PJ": "Depositario Provisional PJ",
    "R-25-PJ": "Agente Interventor PJ",
    "R-26-PJ": "Agente de Aduanas PJ",
    "R-27-PJ": "Funcionario delegado para cumplir funciones OEA PJ",
    "R-99-PJ": "Otro tipo de responsable PJ",
}
