# -*- coding: utf-8 -*-

# 8.14. Tipos de Obligaciones-Responsabilidades

LIABILITY_TYPES = {
    "O-01": "Aporte especial para la administración de justicia",
    "O-02": "Gravamen a los movimientos financieros",
    "O-03": "Impuesto al patrimonio",
    "O-04": "Impuesto sobre la renta y complementario régimen tributario especial",
    "O-05": "Impuesto sobre la renta y complementario régimen ordinario",
    "O-06": "Ingresos y patrimonio",
    "O-07": "Retención en la fuente a título de renta",
    "O-08": "Retención timbre nacional",
    "O-09": "Retención en la fuente en el impuesto sobre las ventas",
    "O-10": "Usuario aduanero",
    "O-11": "Ventas régimen común",
    "O-12": "Ventas régimen simplificado",
    "O-13": "Gran contribuyente",
    "O-14": "Informante de exógena",
    "O-15": "Autorretenedor",
    "O-16": "Obligación de facturar por ingresos de bienes y/o servicios excluidos",
    "O-17": "Profesionales de compra y venta de divisas",
    "O-18": "Precios de Transferencia",
    "O-19": "Productor y/o exportador de bienes exentos",
    "O-20": "Obtención NIT",
    "O-21": "Declarar el ingreso o salida del país de divisas o moneda legal colombiana",
    "O-22": "Obligado a cumplir deberes formales a nombre de terceros",
    "O-23": "Agente de retención en el impuesto sobre las ventas",
    "O-24": "Declaración Informativa Consolidada Precios de transferencia",
    "O-26": "Declaración Informativa Individual Precios de transferencia",
    "O-32": "Impuesto Nacional a la Gasolina y al ACPM",
    "O-33": "Impuesto Nacional al consumo",
    "O-34": "Régimen simplificado impuesto nacional consumo rest y bares",
    "O-35": "Impuesto sobre la renta para la equidad CREE",
    "O-36": "Establecimiento Permanente",
    "O-37": "Obligado a Facturar Electrónicamente Modelo 2242",
    "O-38": "Facturación Electrónica Voluntaria Modelo 2242",
    "O-39": "Proveedor de Servicios Tecnológicos PST Modelo 2242",
    "O-40": "Impuesto a la Riqueza",
    "O-41": "Declaración anual de activos en el exterior",
    "O-42": "Obligado a Llevar Contabilidad",
    "O-99": "Otro tipo de obligado",
    "A-41": "Beneficiarios de programas especiales de exportación PEX",
    "A-42": "Depósitos privados para mercancías en tránsito San Andrés",
    "A-43": "Observadores de las operaciones de importación",
    "A-44": "Usuarios sistemas especiales Importación exportación",
    "A-46": "Transportador maritimo régimen de importación y/o exportación",
    "A-47": "Transportador terrestre régimen de importación y/o exportación",
    "A-48": "Aeropuerto de servicio publico o privado",
    "A-49": "Transportador fluvial régimen de importación",
    "A-50": "Usuario industrial zona franca especial",
    "A-53": "Agencias de aduanas 1",
    "A-54": "Usuario Operador Zona Franca Especial",
    "A-55": "Agencias de aduanas 2",
    "A-56": "Agencias de aduanas 3",
    "A-57": "Agencias de aduanas 4",
    "A-58": "Transportador aéreo nacional",
    "A-60": "Transportador aéreo, marítimo o fluvial modalidad Cabotaje",
    "A-61": "Importador de alimentos de consumo humano y animal",
    "A-62": "Importador Ocasional",
    "A-63": "Importador de maquinaría y sus partes Decreto 2261 de 2012",
    "A-64": "Beneficiario Programa de Fomento Industria Automotriz-PROFIA",
    "A-99": "Otro tipo de agente aduanero",
}
