# 8.15. Tipos de Usuarios Aduaneros

CUSTOMS_USERS_TYPES = {
    "A-01": "Agente de carga internacional",
    "A-02": "Agente marítimo",
    "A-03": "Almacén general de depósito",
    "A-04": "Comercializadora internacional(C.I.)",
    "A-05": "Comerciante de la zona aduanera especial de Inírida, Puerto "
    "Carre&ntildeo, Cumaribo y Primavera",
    "A-06": "Comerciantes de la zona de régimen aduanero especial de Leticia",
    "A-07": "Comerciantes de la zona de régimen aduanero especial de Maicao, "
    "Uribia y Manaure",
    "A-08": "Comerciantes de la zona de régimen aduanero especial de Urabá, "
    "Tumaco y Guapí",
    "A-09": "Comerciantes del puerto libre de San Andrés, Providencia y Santa Catalina",
    "A-10": "Depósito público de apoyo logístico internacional",
    "A-11": "Depósito privado para procesamiento industrial",
    "A-12": "Depósito privado de transformación o ensamble",
    "A-13": "Depósito franco",
    "A-14": "Depósito privado aeronáutico",
    "A-15": "Depósito privado para distribución internacional",
    "A-16": "Depósito privado de provisiones de a bordo para consumo y para llevar",
    "A-17": "Depósito privado para envíos urgentes",
    "A-18": "Depósito privado",
    "A-19": "Depósito público",
    "A-20": "Depósito público para distribución internacional",
    "A-21": "Exportador de café",
    "A-22": "Exportador",
    "A-23": "Importador",
    "A-24": "Intermediario de tráfico postal y envíos urgentes",
    "A-25": "Operador de transporte multimodal",
    "A-26": "Sociedad de intermediación aduanera",
    "A-27": "Titular de puertos y muelles de servicio público o privado",
    "A-28": "Transportador aereo régimen de importación y/o exportación",
    "A-29": "Transportista nacional para operaciones del régimen de tránsito aduanero",
    "A-30": "Usuario comercial zona franca",
    "A-32": "Usuario industrial de bienes zona franca",
    "A-34": "Usuario industrial de servicios zona franca",
    "A-36": "Usuario operador de zona franca",
    "A-37": "Usuario aduanero permanente",
    "A-38": "Usuario altamente exportador",
    "A-39": "Usuario de zonas económicas especiales de exportación",
    "A-40": "Deposito privado de instalaciones industriales",
    "A-41": "Beneficiarios de programas especiales de exportación PEX",
    "A-42": "Depósitos privados para mercancías en tránsito San Andrés",
    "A-43": "Observadores de las operaciones de importación",
    "A-44": "Usuarios sistemas especiales Importación exportación",
    "A-46": "Transportador maritimo régimen de importación y/o exportación",
    "A-47": "Transportador terrestre régimen de importación y/o exportación",
    "A-48": "Aeropuerto de servicio publico o privado",
    "A-49": "Transportador fluvial régimen de importación",
    "A-50": "Usuario industrial zona franca especial",
    "A-53": "Agencias de aduanas 1",
    "A-54": "Usuario Operador Zona Franca Especial",
    "A-55": "Agencias de aduanas 2",
    "A-56": "Agencias de aduanas 3",
    "A-57": "Agencias de aduanas 4",
    "A-58": "Transportador aéreo nacional",
    "A-60": "Transportador aéreo, marítimo o fluvial modalidad Cabotaje",
    "A-61": "Importador de alimentos de consumo humano y animal",
    "A-62": "Importador Ocasional",
    "A-63": "Importador de maquinaría y sus partes Decreto 2261 de 2012",
    "A-64": "Beneficiario Programa de Fomento Industria Automotriz-PROFIA",
    "A-99": "Otro tipo de agente aduanero",
}
